[package]
name = "rscpf/rbxtrace"
version = "0.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A comprehensive, production-ready logging system for Roblox games with advanced features like real-time GUI monitoring, DataStore persistence, webhook alerts, and intelligent filtering."
license = "MIT"
exclude = ["examples", "Packages", ".github", "build", "*.zip", ".git", "wally.lock", "default.project.json", ".gitignore"]

[dependencies]
Red = "red-blox/red@^2.3.2"